#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("conseilMoi.Resource", IsApplication=true)]

namespace conseilMoi
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::conseilMoi.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::conseilMoi.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::conseilMoi.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Historique = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int iconeTest = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Profil = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Scan = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Synthese = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060013
			public const int LinearList = 2131099667;
			
			// aapt resource value: 0x7f060021
			public const int button1 = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int button2 = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int button3 = 2131099683;
			
			// aapt resource value: 0x7f060004
			public const int buttonMajBase = 2131099652;
			
			// aapt resource value: 0x7f060036
			public const int contentFrame = 2131099702;
			
			// aapt resource value: 0x7f06000a
			public const int imageViewAvertissementAvertissement = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int imageViewAvertissementConseil = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int imageViewAvertissementHistorique = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int imageViewAvertissementProfil = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int imageViewAvertissementScann = 2131099656;
			
			// aapt resource value: 0x7f060012
			public const int imageViewConseilAvertissement = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int imageViewConseilConseil = 2131099665;
			
			// aapt resource value: 0x7f06000f
			public const int imageViewConseilHistorique = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int imageViewConseilProfil = 2131099662;
			
			// aapt resource value: 0x7f060010
			public const int imageViewConseilScann = 2131099664;
			
			// aapt resource value: 0x7f06001b
			public const int imageViewHistoriqueAvertissement = 2131099675;
			
			// aapt resource value: 0x7f06001a
			public const int imageViewHistoriqueConseil = 2131099674;
			
			// aapt resource value: 0x7f060018
			public const int imageViewHistoriqueHistorique = 2131099672;
			
			// aapt resource value: 0x7f060017
			public const int imageViewHistoriqueProfil = 2131099671;
			
			// aapt resource value: 0x7f060019
			public const int imageViewHistoriqueScann = 2131099673;
			
			// aapt resource value: 0x7f06002d
			public const int imageViewProduitAvertissement = 2131099693;
			
			// aapt resource value: 0x7f06002c
			public const int imageViewProduitConseil = 2131099692;
			
			// aapt resource value: 0x7f06002a
			public const int imageViewProduitHistorique = 2131099690;
			
			// aapt resource value: 0x7f060029
			public const int imageViewProduitProfil = 2131099689;
			
			// aapt resource value: 0x7f06002b
			public const int imageViewProduitScann = 2131099691;
			
			// aapt resource value: 0x7f060035
			public const int imageViewProfilAvertissement = 2131099701;
			
			// aapt resource value: 0x7f060034
			public const int imageViewProfilConseil = 2131099700;
			
			// aapt resource value: 0x7f060032
			public const int imageViewProfilHistorique = 2131099698;
			
			// aapt resource value: 0x7f060031
			public const int imageViewProfilProfil = 2131099697;
			
			// aapt resource value: 0x7f060033
			public const int imageViewProfilScann = 2131099699;
			
			// aapt resource value: 0x7f06001c
			public const int linearLayout1 = 2131099676;
			
			// aapt resource value: 0x7f06002f
			public const int linearLayoutBilanDesCirters = 2131099695;
			
			// aapt resource value: 0x7f06002e
			public const int linearLayoutProfile = 2131099694;
			
			// aapt resource value: 0x7f060014
			public const int listView = 2131099668;
			
			// aapt resource value: 0x7f060005
			public const int menuAvertissement = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int menuAvertissementProduit = 2131099650;
			
			// aapt resource value: 0x7f06000d
			public const int menuConseil = 2131099661;
			
			// aapt resource value: 0x7f060016
			public const int menuHistorique = 2131099670;
			
			// aapt resource value: 0x7f060024
			public const int menuProduitInfos = 2131099684;
			
			// aapt resource value: 0x7f060030
			public const int menuProfil = 2131099696;
			
			// aapt resource value: 0x7f06001d
			public const int space1 = 2131099677;
			
			// aapt resource value: 0x7f06001f
			public const int space2 = 2131099679;
			
			// aapt resource value: 0x7f06000b
			public const int textView1 = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int textView2 = 2131099660;
			
			// aapt resource value: 0x7f060020
			public const int textView3 = 2131099680;
			
			// aapt resource value: 0x7f06001e
			public const int textView4 = 2131099678;
			
			// aapt resource value: 0x7f060001
			public const int textViewAvertissementTexte = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int textViewAvertissementTitre = 2131099648;
			
			// aapt resource value: 0x7f060015
			public const int textViewHistoriqueTitre = 2131099669;
			
			// aapt resource value: 0x7f060025
			public const int textViewIdProduit = 2131099685;
			
			// aapt resource value: 0x7f060003
			public const int textViewIdProduitAv = 2131099651;
			
			// aapt resource value: 0x7f060027
			public const int textViewInfoAlergene = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int textViewInfoNutriment = 2131099688;
			
			// aapt resource value: 0x7f060026
			public const int textViewInfoScan = 2131099686;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Avertissement = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Conseil = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Historique = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ListViewDataHistorique = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Produit = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Profil = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int zxingscanneractivitylayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int zxingscannerfragmentlayout = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int data = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
